name: project_timer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  numberpicker: ^2.1.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  window_manager: ^0.3.7
  flutter_ringtone_player: ^4.0.0+4
  wakelock_plus: ^1.3.3
  timezone: ^0.9.4
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  device_info_plus: ^11.3.0
  flutter_timezone: ^4.1.1
  package_info_plus: ^8.3.1
  # Pexels 图片浏览器依赖
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/timer_finish.mp3
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/3.jpeg
    - assets/images/4.jpeg
  fonts:
    - family: Orbitron-Regular
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
